server:
  port: 30007

spring:
  application:
    name: post-like-service
  datasource:
    url: jdbc:mysql://localhost:3306/ToyWechat_Post_Like?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 32
        max-idle: 6
        max-wait: 100
        min-idle: 4
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.post_like_service.dao


management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true

