server:
  port: 9800

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:3000"
#            allowedMethods: "*"
#            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: friend_service
          uri: lb://friend-service
          predicates:
            - Path=/friend_service/**/**
        - id: user_service
          uri: lb://user-service
          predicates:
            - Path=/user_service/**/**
        - id: message_service
          uri: lb://message-service
          predicates:
            - Path=/message_service/**/**
        - id: post_like_service
          uri: lb://post-like-service
          predicates:
            - Path=/post_like_service/**/**
        - id: post_comment_service
          uri: lb://post-comment-service
          predicates:
            - Path=/post_comment_service/**/**
        - id: post_content_service
          uri: lb://post-content-service
          predicates:
            - Path=/post_content_service/**/**
        - id: request_service
          uri: lb://request-service
          predicates:
            - Path=/request_service/**/**



