package org.example.friend_service.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.commonUtils.entity.Friend;
import org.example.commonUtils.entity.FriendExample;

public interface FriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    long countByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    int deleteByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("userId") String userId, @Param("friendId") String friendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    int insert(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    int insertSelective(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    List<Friend> selectByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    Friend selectByPrimaryKey(@Param("id") Integer id, @Param("userId") String userId, @Param("friendId") String friendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    int updateByExampleSelective(@Param("record") Friend record, @Param("example") FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    int updateByExample(@Param("record") Friend record, @Param("example") FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    int updateByPrimaryKeySelective(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    int updateByPrimaryKey(Friend record);
}