package org.example.post_comment_service.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.commonUtils.entity.PostComment;
import org.example.commonUtils.entity.PostCommentExample;

public interface PostCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    long countByExample(PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    int deleteByExample(PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    int insert(PostComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    int insertSelective(PostComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    List<PostComment> selectByExample(PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    PostComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    int updateByExampleSelective(@Param("record") PostComment record, @Param("example") PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    int updateByExample(@Param("record") PostComment record, @Param("example") PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    int updateByPrimaryKeySelective(PostComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    int updateByPrimaryKey(PostComment record);



    List<PostComment> getPostCommentsAfterID(@Param("pid") String pid, @Param("id") Integer id);
}