server:
  port: 30002

spring:
  application:
    name: friend-service
  datasource:
    url: jdbc:mysql://localhost:3306/ToyWechat_Friend?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.friend_service.dao


management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true

