package org.example.post_like_service.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.commonUtils.entity.PostLike;
import org.example.commonUtils.entity.PostLikeExample;

public interface PostLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_like
     *
     * @mbg.generated Sun May 22 12:58:12 EDT 2022
     */
    long countByExample(PostLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_like
     *
     * @mbg.generated Sun May 22 12:58:12 EDT 2022
     */
    int deleteByExample(PostLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_like
     *
     * @mbg.generated Sun May 22 12:58:12 EDT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_like
     *
     * @mbg.generated Sun May 22 12:58:12 EDT 2022
     */
    int insert(PostLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_like
     *
     * @mbg.generated Sun May 22 12:58:12 EDT 2022
     */
    int insertSelective(PostLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_like
     *
     * @mbg.generated Sun May 22 12:58:12 EDT 2022
     */
    List<PostLike> selectByExample(PostLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_like
     *
     * @mbg.generated Sun May 22 12:58:12 EDT 2022
     */
    PostLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_like
     *
     * @mbg.generated Sun May 22 12:58:12 EDT 2022
     */
    int updateByExampleSelective(@Param("record") PostLike record, @Param("example") PostLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_like
     *
     * @mbg.generated Sun May 22 12:58:12 EDT 2022
     */
    int updateByExample(@Param("record") PostLike record, @Param("example") PostLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_like
     *
     * @mbg.generated Sun May 22 12:58:12 EDT 2022
     */
    int updateByPrimaryKeySelective(PostLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_like
     *
     * @mbg.generated Sun May 22 12:58:12 EDT 2022
     */
    int updateByPrimaryKey(PostLike record);


}