package org.example.commonUtils.entity;

public class Friend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.id
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.user_id
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.friend_id
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    private String friendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.topic_id
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    private String topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.hide_myself
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    private Boolean hideMyself;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.block_opposite
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    private Boolean blockOpposite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.in_chatting
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    private Boolean inChatting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.valid
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.id
     *
     * @return the value of friend.id
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.id
     *
     * @param id the value for friend.id
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.user_id
     *
     * @return the value of friend.user_id
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.user_id
     *
     * @param userId the value for friend.user_id
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.friend_id
     *
     * @return the value of friend.friend_id
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public String getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.friend_id
     *
     * @param friendId the value for friend.friend_id
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public void setFriendId(String friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.topic_id
     *
     * @return the value of friend.topic_id
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public String getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.topic_id
     *
     * @param topicId the value for friend.topic_id
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public void setTopicId(String topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.hide_myself
     *
     * @return the value of friend.hide_myself
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public Boolean getHideMyself() {
        return hideMyself;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.hide_myself
     *
     * @param hideMyself the value for friend.hide_myself
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public void setHideMyself(Boolean hideMyself) {
        this.hideMyself = hideMyself;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.block_opposite
     *
     * @return the value of friend.block_opposite
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public Boolean getBlockOpposite() {
        return blockOpposite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.block_opposite
     *
     * @param blockOpposite the value for friend.block_opposite
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public void setBlockOpposite(Boolean blockOpposite) {
        this.blockOpposite = blockOpposite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.in_chatting
     *
     * @return the value of friend.in_chatting
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public Boolean getInChatting() {
        return inChatting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.in_chatting
     *
     * @param inChatting the value for friend.in_chatting
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public void setInChatting(Boolean inChatting) {
        this.inChatting = inChatting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.valid
     *
     * @return the value of friend.valid
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.valid
     *
     * @param valid the value for friend.valid
     *
     * @mbg.generated Wed Jul 27 19:27:45 EDT 2022
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}