package org.example.commonUtils.entity;

import java.time.LocalDateTime;

public class PostComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_comment.id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_comment.post_comment_id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    private String postCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_comment.post_content_id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    private String postContentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_comment.user_id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_comment.user2_id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    private String user2Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_comment.comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_comment.create_time
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    private LocalDateTime createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_comment.id
     *
     * @return the value of post_comment.id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_comment.id
     *
     * @param id the value for post_comment.id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_comment.post_comment_id
     *
     * @return the value of post_comment.post_comment_id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public String getPostCommentId() {
        return postCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_comment.post_comment_id
     *
     * @param postCommentId the value for post_comment.post_comment_id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public void setPostCommentId(String postCommentId) {
        this.postCommentId = postCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_comment.post_content_id
     *
     * @return the value of post_comment.post_content_id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public String getPostContentId() {
        return postContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_comment.post_content_id
     *
     * @param postContentId the value for post_comment.post_content_id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public void setPostContentId(String postContentId) {
        this.postContentId = postContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_comment.user_id
     *
     * @return the value of post_comment.user_id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_comment.user_id
     *
     * @param userId the value for post_comment.user_id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_comment.user2_id
     *
     * @return the value of post_comment.user2_id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public String getUser2Id() {
        return user2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_comment.user2_id
     *
     * @param user2Id the value for post_comment.user2_id
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public void setUser2Id(String user2Id) {
        this.user2Id = user2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_comment.comment
     *
     * @return the value of post_comment.comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_comment.comment
     *
     * @param comment the value for post_comment.comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_comment.create_time
     *
     * @return the value of post_comment.create_time
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_comment.create_time
     *
     * @param createTime the value for post_comment.create_time
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }
}