package org.example.commonUtils.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PostCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public PostCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPostCommentIdIsNull() {
            addCriterion("post_comment_id is null");
            return (Criteria) this;
        }

        public Criteria andPostCommentIdIsNotNull() {
            addCriterion("post_comment_id is not null");
            return (Criteria) this;
        }

        public Criteria andPostCommentIdEqualTo(String value) {
            addCriterion("post_comment_id =", value, "postCommentId");
            return (Criteria) this;
        }

        public Criteria andPostCommentIdNotEqualTo(String value) {
            addCriterion("post_comment_id <>", value, "postCommentId");
            return (Criteria) this;
        }

        public Criteria andPostCommentIdGreaterThan(String value) {
            addCriterion("post_comment_id >", value, "postCommentId");
            return (Criteria) this;
        }

        public Criteria andPostCommentIdGreaterThanOrEqualTo(String value) {
            addCriterion("post_comment_id >=", value, "postCommentId");
            return (Criteria) this;
        }

        public Criteria andPostCommentIdLessThan(String value) {
            addCriterion("post_comment_id <", value, "postCommentId");
            return (Criteria) this;
        }

        public Criteria andPostCommentIdLessThanOrEqualTo(String value) {
            addCriterion("post_comment_id <=", value, "postCommentId");
            return (Criteria) this;
        }

        public Criteria andPostCommentIdLike(String value) {
            addCriterion("post_comment_id like", value, "postCommentId");
            return (Criteria) this;
        }

        public Criteria andPostCommentIdNotLike(String value) {
            addCriterion("post_comment_id not like", value, "postCommentId");
            return (Criteria) this;
        }

        public Criteria andPostCommentIdIn(List<String> values) {
            addCriterion("post_comment_id in", values, "postCommentId");
            return (Criteria) this;
        }

        public Criteria andPostCommentIdNotIn(List<String> values) {
            addCriterion("post_comment_id not in", values, "postCommentId");
            return (Criteria) this;
        }

        public Criteria andPostCommentIdBetween(String value1, String value2) {
            addCriterion("post_comment_id between", value1, value2, "postCommentId");
            return (Criteria) this;
        }

        public Criteria andPostCommentIdNotBetween(String value1, String value2) {
            addCriterion("post_comment_id not between", value1, value2, "postCommentId");
            return (Criteria) this;
        }

        public Criteria andPostContentIdIsNull() {
            addCriterion("post_content_id is null");
            return (Criteria) this;
        }

        public Criteria andPostContentIdIsNotNull() {
            addCriterion("post_content_id is not null");
            return (Criteria) this;
        }

        public Criteria andPostContentIdEqualTo(String value) {
            addCriterion("post_content_id =", value, "postContentId");
            return (Criteria) this;
        }

        public Criteria andPostContentIdNotEqualTo(String value) {
            addCriterion("post_content_id <>", value, "postContentId");
            return (Criteria) this;
        }

        public Criteria andPostContentIdGreaterThan(String value) {
            addCriterion("post_content_id >", value, "postContentId");
            return (Criteria) this;
        }

        public Criteria andPostContentIdGreaterThanOrEqualTo(String value) {
            addCriterion("post_content_id >=", value, "postContentId");
            return (Criteria) this;
        }

        public Criteria andPostContentIdLessThan(String value) {
            addCriterion("post_content_id <", value, "postContentId");
            return (Criteria) this;
        }

        public Criteria andPostContentIdLessThanOrEqualTo(String value) {
            addCriterion("post_content_id <=", value, "postContentId");
            return (Criteria) this;
        }

        public Criteria andPostContentIdLike(String value) {
            addCriterion("post_content_id like", value, "postContentId");
            return (Criteria) this;
        }

        public Criteria andPostContentIdNotLike(String value) {
            addCriterion("post_content_id not like", value, "postContentId");
            return (Criteria) this;
        }

        public Criteria andPostContentIdIn(List<String> values) {
            addCriterion("post_content_id in", values, "postContentId");
            return (Criteria) this;
        }

        public Criteria andPostContentIdNotIn(List<String> values) {
            addCriterion("post_content_id not in", values, "postContentId");
            return (Criteria) this;
        }

        public Criteria andPostContentIdBetween(String value1, String value2) {
            addCriterion("post_content_id between", value1, value2, "postContentId");
            return (Criteria) this;
        }

        public Criteria andPostContentIdNotBetween(String value1, String value2) {
            addCriterion("post_content_id not between", value1, value2, "postContentId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUser2IdIsNull() {
            addCriterion("user2_id is null");
            return (Criteria) this;
        }

        public Criteria andUser2IdIsNotNull() {
            addCriterion("user2_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser2IdEqualTo(String value) {
            addCriterion("user2_id =", value, "user2Id");
            return (Criteria) this;
        }

        public Criteria andUser2IdNotEqualTo(String value) {
            addCriterion("user2_id <>", value, "user2Id");
            return (Criteria) this;
        }

        public Criteria andUser2IdGreaterThan(String value) {
            addCriterion("user2_id >", value, "user2Id");
            return (Criteria) this;
        }

        public Criteria andUser2IdGreaterThanOrEqualTo(String value) {
            addCriterion("user2_id >=", value, "user2Id");
            return (Criteria) this;
        }

        public Criteria andUser2IdLessThan(String value) {
            addCriterion("user2_id <", value, "user2Id");
            return (Criteria) this;
        }

        public Criteria andUser2IdLessThanOrEqualTo(String value) {
            addCriterion("user2_id <=", value, "user2Id");
            return (Criteria) this;
        }

        public Criteria andUser2IdLike(String value) {
            addCriterion("user2_id like", value, "user2Id");
            return (Criteria) this;
        }

        public Criteria andUser2IdNotLike(String value) {
            addCriterion("user2_id not like", value, "user2Id");
            return (Criteria) this;
        }

        public Criteria andUser2IdIn(List<String> values) {
            addCriterion("user2_id in", values, "user2Id");
            return (Criteria) this;
        }

        public Criteria andUser2IdNotIn(List<String> values) {
            addCriterion("user2_id not in", values, "user2Id");
            return (Criteria) this;
        }

        public Criteria andUser2IdBetween(String value1, String value2) {
            addCriterion("user2_id between", value1, value2, "user2Id");
            return (Criteria) this;
        }

        public Criteria andUser2IdNotBetween(String value1, String value2) {
            addCriterion("user2_id not between", value1, value2, "user2Id");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post_comment
     *
     * @mbg.generated do_not_delete_during_merge Sun May 22 17:17:07 EDT 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post_comment
     *
     * @mbg.generated Sun May 22 17:17:07 EDT 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}