package org.example.commonUtils.entity;

import java.time.LocalDateTime;

public class Request {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.id
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.request_user_id
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    private String requestUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.handle_user_id
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    private String handleUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.status
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.create_time
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    private LocalDateTime createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.id
     *
     * @return the value of request.id
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.id
     *
     * @param id the value for request.id
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.request_user_id
     *
     * @return the value of request.request_user_id
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    public String getRequestUserId() {
        return requestUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.request_user_id
     *
     * @param requestUserId the value for request.request_user_id
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    public void setRequestUserId(String requestUserId) {
        this.requestUserId = requestUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.handle_user_id
     *
     * @return the value of request.handle_user_id
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    public String getHandleUserId() {
        return handleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.handle_user_id
     *
     * @param handleUserId the value for request.handle_user_id
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    public void setHandleUserId(String handleUserId) {
        this.handleUserId = handleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.status
     *
     * @return the value of request.status
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.status
     *
     * @param status the value for request.status
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.create_time
     *
     * @return the value of request.create_time
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.create_time
     *
     * @param createTime the value for request.create_time
     *
     * @mbg.generated Wed Jul 27 19:35:52 EDT 2022
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }
}